import "~/styles/globals.css";
import { cn } from "../lib/utils"

import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "../components/ui/Othercomponents/Navbar";
import SessionProvider from "../components/ui/Othercomponents/SessionProvider";
import { ThemeProvider } from "~/components/ui/theme-provider";
import { ModeToggle } from "~/components/ui/mode-toggle";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en" className="light">
      <body className={cn('min-h-screen font-sans antialiased grainy', inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <SessionProvider session={session}>
            <TRPCReactProvider>
              <Navbar />
              <ModeToggle />
              {children}
            </TRPCReactProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

